#ABNF 1.0 UTF-8;
language zh-CN; 
mode voice;

root $main;
$main = $english[$english][$english][$english][$english][$english][$english][$english][$english][$english][$english][$english][$english][$english][$english][$english];
$english = a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z;